### ISSUE TITLE
Licence enforcing Linagora/Twake advertisements on every outbound messages(mails, meeting requests)

### ISSUE THREAD

**Issue by samir-s** [Twake/Twake#675]
As seen in the licence : "In accordance with Section 7 and subsection (b) of the GNU Affero General Public License version 3, these Appropriate Legal Notices consist in the display of the Signature Notice “Twake is powered by Linagora.” for any and all type of outbound messages (e.g. e-mail and meeting requests). Retaining this Signature Notice in any and all free and Open Source versions of Twake is mandatory notwhistanding any other terms and conditions."

It's definitely a NO GO for me, even if the source code is open.

See here for a discussion:
https://opensource.stackexchange.com/questions/5562/is-there-a-free-use-with-advertisement-license

No major known opensource project will enforce such a "obnoxious" clause. 

I suggest the founders to reconsider their positions, or to bear the consequences: I'm pretty convinced that most part of the FOSS community would reject such a clause, and would avoid playing the advertising panel for the project's company.

**Comment by cheerios911** [comment]
You can reference this ticket here, it should solve your question.

https://github.com/TwakeApp/Twake/issues/584

**Comment by samir-s** [comment]
I was first attracted by this project, and considering the position of the company according to the ticket you've mentioned, I'm going far far away... 

I'm pretty sure that most of the time, at the beginning of this new project, when a possible foss contributor would stumble upon this clause, he won't continue to contribute. I knew Twake for months, and wasn't aware about this clause till I've discovered this clause in a blog comment. Be sure that this knowledge will quickly spread on major foss community hubs, and permanently damaging the company reputation in foss community, ironically because of its attempt to enforce its branding ads. 

I think the organization behind this project doesn't get what "commons" mean, and does not understand the foss culture. It means "let it go and give it to mankind" humble stance, it does not mean enforcing human beings and organizations to put the project's company in the spotlight.

This so-called "foss" project is shooting itself in the foot at the very beginning.

**Comment by RomaricMourgues** [comment]
Thanks for your feedback, we are new (the Twake team) in the open-source community, we'll bring your points to Linagora and I hope they'll be able to clarify and update everything soon. For your information we got this license from LinShare originally and at the time they did not had such feedback from their community.

I am very sorry for this, we are mainly a team of developers that want to do a great open-source alternative to Teams, I assure you that it must be a mistake and I don't see any reason why we could not change it 😃 

We have still a lot of work to do to finish our transition to the open-source community and to our new company Linagora. We do not control the news and even if we are very happy to see so many feedback, we still have a lot to do.
So thank you very much for your feedback again :)
We keep you updated!

**Comment by RomaricMourgues** [comment]
Oh by the way @samir-s you mention a blog comment also? I am listing the feedback on this point in order to fix this as soon as possible, if you have a link or something for me to bring it up to the legal team of Linagora?

The point become critical like you said, so I will take action on my side.

**Comment by samir-s** [comment]
Glad to hear this openness. 

The FOSS community has its rituals, habits, and values: take the time to study it, or hire a seasoned foss developer or consultant... Foss community is different than the open-source community: opening the source code does not imply that your project carries free/Libre culture values. 

My advice, if you are new to the foss community, would be to just follow the path of major FOSS project, like Linux, Nextcloud, etc. I would not try to invent or adapt the licence at all, and just stick to the original AGPLv3 like the major FOSS project.  

You can't be wrong by following the path of FOSS giants.

About the blog url link: https://itsfoss.com/twake-app/

**Comment by cheerios911** [comment]
> I am very sorry for this, we are mainly a team of developers that want to do a great open-source alternative to Teams, I assure you that it must be a mistake and **_I don't see any reason why we could not change it_** 😃

@RomaricMourgues and @BenoitTallandier ?  maybe when you guys go back to Linagora, tell them it's probably best to remove that language as well from openpaas and linshare.  It would be great for someone else not to spend thousands of dollars on reviewing your language like i did or other users did as well.

**Comment by teach-ed** [comment]
@cheerios911 Linagora may make their code open source but they market their products as a SAAS offering.  

That language has been there for quite sometime and I believe they open source their code to give trust to their target customers not to build a community.  

And that's OK, accept that and move on if you don't wish to brand their products or use them. Its their code at the end of the day mate, and as samir pointed out, the community doesn't work in that manner.  

I spent a lot of money on legal, not to mention quite a bit developing onto JAMES.  But you don't hear me complaining. I simply moved on and an focusing on actual fully open source environments, I suggest you do the same. 

Thanks mate, and if you don't mind, please stop bringing tickets I'm linked to in other conversations.  I don't mind, but I don't wish to get notifications on projects I don't work on any longer.

**Comment by cheerios911** [comment]
sorry @teach-ed , not trying to pull you into more conversation or come off as complaining.  I only came across this legal language because of your open ticket at openpaas which led me to getting a legal review. 

the language was written in a way that someone who doesn't get legal help on it could have been put into major liability unknowingly.  I'm just being proactive in pointing it out when others raise the question so they too don't have to spend the money.  

Openpaas was bit too finnicky to develop on IMO so I can't imagine how much you spent timewise or moneywise to just stop.  Hopefully your attorney didn't charge as much as mine did 😭 😆

**Comment by teach-ed** [comment]
Openpaas has the identical amendment as linshare and twake.

While they show the v3 of the license on the main repo page, you have to look at the license that ships with the files.  We initially thought they changed that which is why I closed my ticket, however they just removed that language from the page, not the true license that comes with the software download.  Always make sure to read that mate.  Twake was kind enough to put that on their page openly. So you should have been aware from the get go.  

And no, we did not stop developing on JAMES, openpaas was the only known implementation of it which is why we chose them, but that language had us run for the hills.  Linagora does not own apache James, they just contribute massively to its development.  👍🏻

**Comment by AisukoWasTaken** [comment]
I think there is history behind the language.
Linagora had an issue with BlueMind that allegedly reused most of their OBM Software code and removed all reference of Linagora. I'm guessing this protection against that.
To be clear, I am not defending Linagora here, I too, believe that this is a bit too much to enforce trademarks in outgoing mail that is supposed to be used by Companies that requires some sort of branding.

**Comment by teach-ed** [comment]
That maybe the case, but again, that happens when you open source code 
and there are many, many other ways to protect your brand on a project 
like this.  the fact that they can sue or pull the license from someone 
at will for using their software should give everyone pause here.

That is the real issue here, not the fact that they demand their brand 
be on the software is not the issue - I can imagine how long it took 
folks like benoit to build a sysetm like this so I could understand that 
they want recognition.  The real issue here is that they include another 
clause in the amendment that says because you use their brand (don't 
forget that they force this on you) that Linagora has the ability to 
pull that license and hold you liable based on *ANY,* let me repeat 
that, any idea that they believe to be hurting the linagora brand.  
That's way too open of a clause, they could say because you believe an 
apple is really a banana that you violated their brand, or maybe they 
just don't like your haircut.  While you think I am joking, these are 
the exact words my attorneys explained to me what their amendment means.

You can't justify an amendment like that by saying they may have been 
hurt in the past.  Stay SAAS if you are worried about someone taking 
your code and using it for something else but don't falsely advertise 
that you are opensource when that just clearly isn't the case.

Sorry Twake guys, I was one of your first downloads of your product and 
really love it - it has so much promise, and I was about to kill our 
instance of rocket chat.  but i'm not touching this project with a 10 ft 
pole with that language.

**Comment by SkanderHelali** [comment]
Yeah, this type of behavior is a no go. I have zero knowledge of who Linagora or what they do, but this is exactly the type of thing that makes me automatically avoid anything they touch.

That's a shame, but at least I found this out before digging myself in.

**Comment by tanandy** [comment]
hi guys i close this as a duplicate from https://github.com/Twake/Twake/issues/584

we will continue the discussion there.
